FROM amd64/python:3.7-alpine
WORKDIR /usr/src/app
COPY requirements.txt ./
RUN pip install -r requirements.txt
COPY . .
ENV MOSQUITTO_HOST mosquitto
ENV MOSQUITTO_PORT 1883
ENV MOSQUITTO_KEEPALIVE 60
ENV GROW_ID 1
ENV GPIOZERO_PIN_FACTORY mock
CMD python -u raspi_consumer.py -h $MOSQUITTO_HOST -p $MOSQUITTO_PORT -k $MOSQUITTO_KEEPALIVE -g $GROW_ID
